// mockTransactions.js
// This file exports an array of mock transaction data for all cards.

export const mockTransactions = [
  // Card 1
  { id: 1, cardId: 1, merchant: 'Starbucks', date: '01 Aug 2025', amount: -6.5, refund: false, color: 'brown', icon: 'local_cafe', location: 'Singapore', category: 'Coffee' },
  { id: 2, cardId: 1, merchant: 'Amazon SG', date: '02 Aug 2025', amount: -120.99, refund: false, color: 'secondary', icon: 'shopping_cart', location: 'Online', category: 'Shopping' },
  { id: 3, cardId: 1, merchant: 'Uber', date: '03 Aug 2025', amount: -18.2, refund: false, color: 'grey', icon: 'directions_car', location: 'Singapore', category: 'Transport' },
  { id: 4, cardId: 1, merchant: 'Netflix', date: '04 Aug 2025', amount: -15.99, refund: false, color: 'red', icon: 'ondemand_video', location: 'Online', category: 'Entertainment' },
  { id: 5, cardId: 1, merchant: 'Starbucks', date: '05 Aug 2025', amount: 6.5, refund: true, color: 'brown', icon: 'local_cafe', location: 'Singapore', category: 'Coffee' },
  { id: 6, cardId: 1, merchant: 'FairPrice', date: '06 Aug 2025', amount: -45.2, refund: false, color: 'green', icon: 'shopping_basket', location: 'Singapore', category: 'Groceries' },
  { id: 7, cardId: 1, merchant: 'Shell', date: '07 Aug 2025', amount: -60.0, refund: false, color: 'yellow', icon: 'local_gas_station', location: 'Singapore', category: 'Fuel' },
  { id: 8, cardId: 1, merchant: 'Decathlon', date: '08 Aug 2025', amount: -80.0, refund: false, color: 'blue', icon: 'sports_soccer', location: 'Singapore', category: 'Sports' },
  { id: 9, cardId: 1, merchant: 'Guardian', date: '09 Aug 2025', amount: -18.0, refund: false, color: 'teal', icon: 'local_pharmacy', location: 'Singapore', category: 'Pharmacy' },
  { id: 10, cardId: 1, merchant: 'IKEA', date: '10 Aug 2025', amount: -150.0, refund: false, color: 'blue', icon: 'weekend', location: 'Singapore', category: 'Furniture' },
  { id: 11, cardId: 1, merchant: 'McDonald’s', date: '11 Aug 2025', amount: -12.5, refund: false, color: 'yellow', icon: 'fastfood', location: 'Singapore', category: 'Food' },
  { id: 12, cardId: 1, merchant: 'Watsons', date: '12 Aug 2025', amount: -32.0, refund: false, color: 'teal', icon: 'local_pharmacy', location: 'Singapore', category: 'Pharmacy' },
  { id: 13, cardId: 1, merchant: 'Grab', date: '13 Aug 2025', amount: -10.0, refund: false, color: 'green', icon: 'directions_car', location: 'Singapore', category: 'Transport' },
  { id: 14, cardId: 1, merchant: 'Cold Storage', date: '14 Aug 2025', amount: -55.0, refund: false, color: 'green', icon: 'shopping_basket', location: 'Singapore', category: 'Groceries' },
  { id: 15, cardId: 1, merchant: 'Uniqlo', date: '15 Aug 2025', amount: -90.0, refund: false, color: 'grey', icon: 'checkroom', location: 'Singapore', category: 'Clothing' },

  // Card 2
  { id: 16, cardId: 2, merchant: 'Apple Store', date: '01 Aug 2025', amount: -999, refund: false, color: 'grey-8', icon: 'phone_iphone', location: 'Singapore', category: 'Electronics' },
  { id: 17, cardId: 2, merchant: 'Swiggy', date: '02 Aug 2025', amount: -23.5, refund: false, color: 'orange', icon: 'restaurant', location: 'India', category: 'Food Delivery' },
  { id: 18, cardId: 2, merchant: 'Flipkart', date: '03 Aug 2025', amount: -199.99, refund: false, color: 'blue', icon: 'shopping_bag', location: 'India', category: 'Shopping' },
  { id: 19, cardId: 2, merchant: 'Big Bazaar', date: '04 Aug 2025', amount: -45.0, refund: false, color: 'primary', icon: 'store', location: 'India', category: 'Groceries' },
  { id: 20, cardId: 2, merchant: 'Flipkart', date: '05 Aug 2025', amount: 199.99, refund: true, color: 'blue', icon: 'shopping_bag', location: 'India', category: 'Shopping' },
  { id: 21, cardId: 2, merchant: 'Watsons', date: '06 Aug 2025', amount: -32.0, refund: false, color: 'teal', icon: 'local_pharmacy', location: 'Singapore', category: 'Pharmacy' },
  { id: 22, cardId: 2, merchant: 'McDonald’s', date: '07 Aug 2025', amount: -12.5, refund: false, color: 'yellow', icon: 'fastfood', location: 'Singapore', category: 'Food' },
  { id: 23, cardId: 2, merchant: 'Starbucks', date: '08 Aug 2025', amount: -7.25, refund: false, color: 'brown', icon: 'local_cafe', location: 'Singapore', category: 'Coffee' },
  { id: 24, cardId: 2, merchant: 'Shell', date: '09 Aug 2025', amount: -60.0, refund: false, color: 'yellow', icon: 'local_gas_station', location: 'Singapore', category: 'Fuel' },
  { id: 25, cardId: 2, merchant: 'Uniqlo', date: '10 Aug 2025', amount: -90.0, refund: false, color: 'grey', icon: 'checkroom', location: 'Singapore', category: 'Clothing' },
  { id: 26, cardId: 2, merchant: 'IKEA', date: '11 Aug 2025', amount: -150.0, refund: false, color: 'blue', icon: 'weekend', location: 'Singapore', category: 'Furniture' },
  { id: 27, cardId: 2, merchant: 'Guardian', date: '12 Aug 2025', amount: -18.0, refund: false, color: 'teal', icon: 'local_pharmacy', location: 'Singapore', category: 'Pharmacy' },
  { id: 28, cardId: 2, merchant: 'Grab', date: '13 Aug 2025', amount: -10.0, refund: false, color: 'green', icon: 'directions_car', location: 'Singapore', category: 'Transport' },
  { id: 29, cardId: 2, merchant: 'Cold Storage', date: '14 Aug 2025', amount: -55.0, refund: false, color: 'green', icon: 'shopping_basket', location: 'Singapore', category: 'Groceries' },
  { id: 30, cardId: 2, merchant: 'Decathlon', date: '15 Aug 2025', amount: -80.0, refund: false, color: 'blue', icon: 'sports_soccer', location: 'Singapore', category: 'Sports' },

  // Card 3
  { id: 31, cardId: 3, merchant: 'Zomato', date: '01 Aug 2025', amount: -30.75, refund: false, color: 'red', icon: 'restaurant', location: 'India', category: 'Food Delivery' },
  { id: 32, cardId: 3, merchant: 'BookMyShow', date: '02 Aug 2025', amount: -12.0, refund: false, color: 'purple', icon: 'movie', location: 'India', category: 'Entertainment' },
  { id: 33, cardId: 3, merchant: 'Hamleys', date: '03 Aug 2025', amount: 50, refund: true, color: 'primary', icon: 'store', location: 'India', category: 'Toys' },
  { id: 34, cardId: 3, merchant: 'Uber', date: '04 Aug 2025', amount: -22.5, refund: false, color: 'grey', icon: 'directions_car', location: 'Singapore', category: 'Transport' },
  { id: 35, cardId: 3, merchant: 'Guardian', date: '05 Aug 2025', amount: -18.0, refund: false, color: 'teal', icon: 'local_pharmacy', location: 'Singapore', category: 'Pharmacy' },
  { id: 36, cardId: 3, merchant: 'IKEA', date: '06 Aug 2025', amount: -150.0, refund: false, color: 'blue', icon: 'weekend', location: 'Singapore', category: 'Furniture' },
  { id: 37, cardId: 3, merchant: 'McDonald’s', date: '07 Aug 2025', amount: -12.5, refund: false, color: 'yellow', icon: 'fastfood', location: 'Singapore', category: 'Food' },
  { id: 38, cardId: 3, merchant: 'Watsons', date: '08 Aug 2025', amount: -32.0, refund: false, color: 'teal', icon: 'local_pharmacy', location: 'Singapore', category: 'Pharmacy' },
  { id: 39, cardId: 3, merchant: 'Grab', date: '09 Aug 2025', amount: -10.0, refund: false, color: 'green', icon: 'directions_car', location: 'Singapore', category: 'Transport' },
  { id: 40, cardId: 3, merchant: 'Cold Storage', date: '10 Aug 2025', amount: -55.0, refund: false, color: 'green', icon: 'shopping_basket', location: 'Singapore', category: 'Groceries' },
  { id: 41, cardId: 3, merchant: 'Uniqlo', date: '11 Aug 2025', amount: -90.0, refund: false, color: 'grey', icon: 'checkroom', location: 'Singapore', category: 'Clothing' },
  { id: 42, cardId: 3, merchant: 'Shell', date: '12 Aug 2025', amount: -60.0, refund: false, color: 'yellow', icon: 'local_gas_station', location: 'Singapore', category: 'Fuel' },
  { id: 43, cardId: 3, merchant: 'Decathlon', date: '13 Aug 2025', amount: -80.0, refund: false, color: 'blue', icon: 'sports_soccer', location: 'Singapore', category: 'Sports' },
  { id: 44, cardId: 3, merchant: 'Starbucks', date: '14 Aug 2025', amount: -6.5, refund: false, color: 'brown', icon: 'local_cafe', location: 'Singapore', category: 'Coffee' },
  { id: 45, cardId: 3, merchant: 'Amazon SG', date: '15 Aug 2025', amount: -120.99, refund: false, color: 'secondary', icon: 'shopping_cart', location: 'Online', category: 'Shopping' },

  // Card 4
  { id: 46, cardId: 4, merchant: 'Myntra', date: '01 Aug 2025', amount: -80.0, refund: false, color: 'pink', icon: 'local_offer', location: 'India', category: 'Shopping' },
  { id: 47, cardId: 4, merchant: 'Hamleys', date: '02 Aug 2025', amount: -150, refund: false, color: 'primary', icon: 'store', location: 'India', category: 'Toys' },
  { id: 48, cardId: 4, merchant: 'Starbucks', date: '03 Aug 2025', amount: -7.25, refund: false, color: 'brown', icon: 'local_cafe', location: 'Singapore', category: 'Coffee' },
  { id: 49, cardId: 4, merchant: 'Myntra', date: '04 Aug 2025', amount: 80.0, refund: true, color: 'pink', icon: 'local_offer', location: 'India', category: 'Shopping' },
  { id: 50, cardId: 4, merchant: 'Cold Storage', date: '05 Aug 2025', amount: -55.0, refund: false, color: 'green', icon: 'shopping_basket', location: 'Singapore', category: 'Groceries' },
  { id: 51, cardId: 4, merchant: 'Grab', date: '06 Aug 2025', amount: -10.0, refund: false, color: 'green', icon: 'directions_car', location: 'Singapore', category: 'Transport' },
  { id: 52, cardId: 4, merchant: 'FairPrice', date: '07 Aug 2025', amount: -45.2, refund: false, color: 'green', icon: 'shopping_basket', location: 'Singapore', category: 'Groceries' },
  { id: 53, cardId: 4, merchant: 'Shell', date: '08 Aug 2025', amount: -60.0, refund: false, color: 'yellow', icon: 'local_gas_station', location: 'Singapore', category: 'Fuel' },
  { id: 54, cardId: 4, merchant: 'Decathlon', date: '09 Aug 2025', amount: -80.0, refund: false, color: 'blue', icon: 'sports_soccer', location: 'Singapore', category: 'Sports' },
  { id: 55, cardId: 4, merchant: 'Guardian', date: '10 Aug 2025', amount: -18.0, refund: false, color: 'teal', icon: 'local_pharmacy', location: 'Singapore', category: 'Pharmacy' },
  { id: 56, cardId: 4, merchant: 'IKEA', date: '11 Aug 2025', amount: -150.0, refund: false, color: 'blue', icon: 'weekend', location: 'Singapore', category: 'Furniture' },
  { id: 57, cardId: 4, merchant: 'McDonald’s', date: '12 Aug 2025', amount: -12.5, refund: false, color: 'yellow', icon: 'fastfood', location: 'Singapore', category: 'Food' },
  { id: 58, cardId: 4, merchant: 'Watsons', date: '13 Aug 2025', amount: -32.0, refund: false, color: 'teal', icon: 'local_pharmacy', location: 'Singapore', category: 'Pharmacy' },
  { id: 59, cardId: 4, merchant: 'Uniqlo', date: '14 Aug 2025', amount: -90.0, refund: false, color: 'grey', icon: 'checkroom', location: 'Singapore', category: 'Clothing' },
  { id: 60, cardId: 4, merchant: 'Amazon SG', date: '15 Aug 2025', amount: -120.99, refund: false, color: 'secondary', icon: 'shopping_cart', location: 'Online', category: 'Shopping' },
];
